CREATE OR REPLACE PROCEDURE CREATEI2B2USER 
is
   cursor c1 is 
      select user_id,first_name,last_name from shibboleth where user_id not in (select user_id from i2b2pm.pm_user_data);

BEGIN
for cu_rec in c1 loop
INSERT INTO I2B2PM.PM_USER_DATA(USER_ID, FULL_NAME, PASSWORD, EMAIL, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
    VALUES(cu_rec.user_id, cu_rec.first_name ||''|| cu_rec.last_name, '9117d59a69dc49807671a51f10ab7f', 
    cu_rec.user_ID, SYSDATE, SYSDATE, 'LDAP', 'A');

INSERT INTO I2B2PM.PM_PROJECT_USER_ROLES(PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD) 
     VALUES('Demo', cu_rec.user_id, 'USER', SYSDATE, SYSDATE, 'LDAP', 'A');
INSERT INTO I2B2PM.PM_PROJECT_USER_ROLES(PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD) 
     VALUES('Demo', cu_rec.user_id, 'DATA_DEID', SYSDATE, SYSDATE, 'LDAP', 'A');
INSERT INTO I2B2PM.PM_PROJECT_USER_ROLES(PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD) 
     VALUES('Demo', cu_rec.user_id, 'DATA_OBFSC', SYSDATE, SYSDATE, 'LDAP', 'A');
INSERT INTO I2B2PM.PM_PROJECT_USER_ROLES(PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD) 
     VALUES('Demo', cu_rec.user_id, 'DATA_AGG', SYSDATE, SYSDATE, 'LDAP', 'A');
INSERT INTO I2B2PM.PM_PROJECT_USER_ROLES(PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD) 
     VALUES('Demo', cu_rec.user_id, 'DATA_LDS', SYSDATE, SYSDATE, 'LDAP', 'A');
END LOOP;
   commit;
END CREATEI2B2USER;
